package com.sv.calorieintakeapps.library_database.domain.model

object MakrotrienData {
    const val ID_KARBOHIDRAT = "total_karbohidrat"
    const val ID_LEMAK = "total_lemak"
    const val ID_AIR = "total_air"
    const val ID_ENERGI = "total_energi"
    const val ID_PROTEIN = "total_protein"
    const val ID_KALSIUM = "kalsium_total"
    const val ID_SERAT = "serat_total"
    const val ID_ABU = "abu_total"
    const val ID_FOSFOR = "fosfor_total"
    const val ID_BESI = "besi_total"
    const val ID_NATRIUM = "natrium_total"
    const val ID_KALIUM = "kalium_total"
    const val ID_TEMBAGA = "tembaga_total"
    const val ID_SENG = "seng_total"
    const val ID_RETINOL = "retinol_total"
    const val ID_BETA_KAROTEN = "beta_karoten_total"
    const val ID_KAROTEN_TOTAL = "karoten_total_total"
    const val ID_THIAMIN = "thiamin_total"
    const val ID_RIFOBLA = "rifobla_total"
    const val ID_NIASIN = "niasin_total"
    const val ID_VITAMIN_C = "vit_c_total"

    // Titles
    const val TITLE_KARBOHIDRAT = "Karbohidrat"
    const val TITLE_LEMAK = "Lemak"
    const val TITLE_AIR = "Air"
    const val TITLE_ENERGI = "Energi"
    const val TITLE_PROTEIN = "Protein"
    const val TITLE_KALSIUM = "Kalsium"
    const val TITLE_SERAT = "Serat"
    const val TITLE_ABU = "Abu"
    const val TITLE_FOSFOR = "Fosfor"
    const val TITLE_BESI = "Besi"
    const val TITLE_NATRIUM = "Natrium"
    const val TITLE_KALIUM = "Kalium"
    const val TITLE_TEMBAGA = "Tembaga"
    const val TITLE_SENG = "Seng"
    const val TITLE_RETINOL = "Retinol"
    const val TITLE_BETA_KAROTEN = "Beta Karoten"
    const val TITLE_KAROTEN_TOTAL = "Karoten"
    const val TITLE_THIAMIN = "Thiamin"
    const val TITLE_RIFOBLA = "Rifobla"
    const val TITLE_NIASIN = "Niasin"
    const val TITLE_VITAMIN_C = "Vitamin C"
}
